<?php
/**
 * IoCallbackType
 *
 * PHP version 5
 *
 * @category Class
 * @package  PkIo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Members API
 *
 * The PassKit Members API lets you manage your membership programs and passes for Apple Wallet and Google Pay.
 *
 * OpenAPI spec version: 1.0-rc
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace PkIo\Model;
use \PkIo\ObjectSerializer;

/**
 * IoCallbackType Class Doc Comment
 *
 * @category Class
 * @package  PkIo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class IoCallbackType
{
    /**
     * Possible values of this enum
     */
    const SEND_EMAIL = 'CALLBACK_TYPE_SEND_EMAIL';
const SEND_SMS = 'CALLBACK_TYPE_SEND_SMS';
const SEND_POST = 'CALLBACK_TYPE_SEND_POST';
const INTEGRATION = 'CALLBACK_TYPE_INTEGRATION';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SEND_EMAIL,
self::SEND_SMS,
self::SEND_POST,
self::INTEGRATION,        ];
    }
}
