<?php
/**
 * IoDistributionSettings
 *
 * PHP version 5
 *
 * @category Class
 * @package  PkIo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Members API
 *
 * The PassKit Members API lets you manage your membership programs and passes for Apple Wallet and Google Pay.
 *
 * OpenAPI spec version: 1.0-rc
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace PkIo\Model;

use \ArrayAccess;
use \PkIo\ObjectSerializer;

/**
 * IoDistributionSettings Class Doc Comment
 *
 * @category Class
 * @package  PkIo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class IoDistributionSettings implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ioDistributionSettings';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'distributionChannels' => '\PkIo\Model\IoDistributionChannel[]',
'welcomeEmail' => '\PkIo\Model\IoEmailTemplate',
'welcomeSms' => '\PkIo\Model\IoSmsTemplate'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'distributionChannels' => null,
'welcomeEmail' => null,
'welcomeSms' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'distributionChannels' => 'distributionChannels',
'welcomeEmail' => 'welcomeEmail',
'welcomeSms' => 'welcomeSms'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'distributionChannels' => 'setDistributionChannels',
'welcomeEmail' => 'setWelcomeEmail',
'welcomeSms' => 'setWelcomeSms'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'distributionChannels' => 'getDistributionChannels',
'welcomeEmail' => 'getWelcomeEmail',
'welcomeSms' => 'getWelcomeSms'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['distributionChannels'] = isset($data['distributionChannels']) ? $data['distributionChannels'] : null;
        $this->container['welcomeEmail'] = isset($data['welcomeEmail']) ? $data['welcomeEmail'] : null;
        $this->container['welcomeSms'] = isset($data['welcomeSms']) ? $data['welcomeSms'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets distributionChannels
     *
     * @return \PkIo\Model\IoDistributionChannel[]
     */
    public function getDistributionChannels()
    {
        return $this->container['distributionChannels'];
    }

    /**
     * Sets distributionChannels
     *
     * @param \PkIo\Model\IoDistributionChannel[] $distributionChannels distributionChannels
     *
     * @return $this
     */
    public function setDistributionChannels($distributionChannels)
    {
        $this->container['distributionChannels'] = $distributionChannels;

        return $this;
    }

    /**
     * Gets welcomeEmail
     *
     * @return \PkIo\Model\IoEmailTemplate
     */
    public function getWelcomeEmail()
    {
        return $this->container['welcomeEmail'];
    }

    /**
     * Sets welcomeEmail
     *
     * @param \PkIo\Model\IoEmailTemplate $welcomeEmail welcomeEmail
     *
     * @return $this
     */
    public function setWelcomeEmail($welcomeEmail)
    {
        $this->container['welcomeEmail'] = $welcomeEmail;

        return $this;
    }

    /**
     * Gets welcomeSms
     *
     * @return \PkIo\Model\IoSmsTemplate
     */
    public function getWelcomeSms()
    {
        return $this->container['welcomeSms'];
    }

    /**
     * Sets welcomeSms
     *
     * @param \PkIo\Model\IoSmsTemplate $welcomeSms welcomeSms
     *
     * @return $this
     */
    public function setWelcomeSms($welcomeSms)
    {
        $this->container['welcomeSms'] = $welcomeSms;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
