<?php
/**
 * IoLinkType
 *
 * PHP version 5
 *
 * @category Class
 * @package  PkIo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Members API
 *
 * The PassKit Members API lets you manage your membership programs and passes for Apple Wallet and Google Pay.
 *
 * OpenAPI spec version: 1.0-rc
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace PkIo\Model;
use \PkIo\ObjectSerializer;

/**
 * IoLinkType Class Doc Comment
 *
 * @category Class
 * @description Used to specify the type of link for link field. Each type has different icon on Google Pay.   - URI_DO_NOT_USE: A link to website.  - URI_WEB: A link to website.  - URI_TEL: A phone number.  - URI_EMAIL: An email address.  - URI_LOCATION: A location address.  - URI_CALENDAR: A calendar event.
 * @package  PkIo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class IoLinkType
{
    /**
     * Possible values of this enum
     */
    const DO_NOT_USE = 'URI_DO_NOT_USE';
const WEB = 'URI_WEB';
const TEL = 'URI_TEL';
const EMAIL = 'URI_EMAIL';
const LOCATION = 'URI_LOCATION';
const CALENDAR = 'URI_CALENDAR';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DO_NOT_USE,
self::WEB,
self::TEL,
self::EMAIL,
self::LOCATION,
self::CALENDAR,        ];
    }
}
