<?php
/**
 * IoProjectStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  PkIo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Members API
 *
 * The PassKit Members API lets you manage your membership programs and passes for Apple Wallet and Google Pay.
 *
 * OpenAPI spec version: 1.0-rc
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace PkIo\Model;
use \PkIo\ObjectSerializer;

/**
 * IoProjectStatus Class Doc Comment
 *
 * @category Class
 * @description - NO_PROJECT_STATUS: Zero based enum, don&#x27;t use 0.  - PROJECT_ACTIVE_FOR_OBJECT_CREATION: Active projects allow for creation of records (turned on by default).  - PROJECT_DISABLED_FOR_OBJECT_CREATION: Disabled projects do not allow for creation of records (i.e. temporarily disable enroling of members / creating of coupons, etc).  - PROJECT_DRAFT: Default status for all projects. A draft project can do everything a published program can: Cards can be created, stats will show up, etc. Data belonging to draft projects is automatically purged every 7 days. A draft project uses a PassKit Apple Developer Certificate, and has a PassKit legal disclaimer on the back. Draft projects cannot be used for a production setup.  - PROJECT_PUBLISHED: A project can only be published if a custom Apple Developer Certificate is uploaded, if payment details have been provided, and an account email address has been validated. Published projects do not have a PassKit legal disclaimer on the back. Published projects do not have their data purged on a 7 day basis.  - PROJECT_PRIVATE: A project is private: records can only by created by authorized users / via the portal interface.  - PROJECT_OVER_QUOTA: The project is currently over quota, and new records cannot be created (set by system only; cannot be set by user)  - PROJECT_DELETED: A project which needs to be deleted. If delete flag is set, project will be deleted in the near future.
 * @package  PkIo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class IoProjectStatus
{
    /**
     * Possible values of this enum
     */
    const NO_PROJECT_STATUS = 'NO_PROJECT_STATUS';
const PROJECT_ACTIVE_FOR_OBJECT_CREATION = 'PROJECT_ACTIVE_FOR_OBJECT_CREATION';
const PROJECT_DISABLED_FOR_OBJECT_CREATION = 'PROJECT_DISABLED_FOR_OBJECT_CREATION';
const PROJECT_DRAFT = 'PROJECT_DRAFT';
const PROJECT_PUBLISHED = 'PROJECT_PUBLISHED';
const PROJECT_PRIVATE = 'PROJECT_PRIVATE';
const PROJECT_OVER_QUOTA = 'PROJECT_OVER_QUOTA';
const PROJECT_DELETED = 'PROJECT_DELETED';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NO_PROJECT_STATUS,
self::PROJECT_ACTIVE_FOR_OBJECT_CREATION,
self::PROJECT_DISABLED_FOR_OBJECT_CREATION,
self::PROJECT_DRAFT,
self::PROJECT_PUBLISHED,
self::PROJECT_PRIVATE,
self::PROJECT_OVER_QUOTA,
self::PROJECT_DELETED,        ];
    }
}
