<?php
/**
 * IoUsageType
 *
 * PHP version 5
 *
 * @category Class
 * @package  PkIo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassKit Members API
 *
 * The PassKit Members API lets you manage your membership programs and passes for Apple Wallet and Google Pay.
 *
 * OpenAPI spec version: 1.0-rc
 * Contact: support@passkit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace PkIo\Model;
use \PkIo\ObjectSerializer;

/**
 * IoUsageType Class Doc Comment
 *
 * @category Class
 * @description - USAGE_APPLE_WALLET: Rendered on Apple Wallet  - USAGE_GOOGLE_PAY: Rendered on Google Pay  - USAGE_DATA_COLLECTION_PAGE: Rendered on data collection page
 * @package  PkIo
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class IoUsageType
{
    /**
     * Possible values of this enum
     */
    const NO_USAGE = 'NO_USAGE';
const USAGE_APPLE_WALLET = 'USAGE_APPLE_WALLET';
const USAGE_GOOGLE_PAY = 'USAGE_GOOGLE_PAY';
const USAGE_DATA_COLLECTION_PAGE = 'USAGE_DATA_COLLECTION_PAGE';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NO_USAGE,
self::USAGE_APPLE_WALLET,
self::USAGE_GOOGLE_PAY,
self::USAGE_DATA_COLLECTION_PAGE,        ];
    }
}
